### ISSUE TITLE
Site can be accessed through unencrypted HTTP

### ISSUE THREAD

**Issue by bdon** [OvertureMaps/io-site#100]
### Description

When visiting http://explore.overturemaps.org (with no `https://`), the site is loaded.

Instead it should redirect to the `https://` site. 

This should be able to configured through CloudFront.

### What browser are you seeing the problem on? What version are you running?

Safari

### The OS you're using

MacOS

### Steps to reproduce

Go to http://explore.overturemaps.org in your browser. 

### The browser URL at the time you encountered the bug

http://explore.overturemaps.org

**Comment by Bonkles** [comment]
Fixed! We should now correctly redirect to https.
