### ISSUE TITLE
Multiple Sources are mashedtogether

### ISSUE THREAD

**Issue by atiannicelli** [OvertureMaps/io-site#104]
### Description

When a building has multiple sources the site is displaying them as one continuous string. They should be separated. 

For instance if you look here: https://explore.overturemaps.org/#16.64/42.655475/-71.141057
And click on any building you will see that the inspector panel looks something like this:
<img width="376" alt="Screenshot 2024-07-23 at 2 52 18 PM" src="https://github.com/user-attachments/assets/25a9b9bd-05ca-42cc-a364-fd23192f8c5d">

But the building that I selected has two separate sources:
```
id: 08b2a30730cc5fff0200a5ec5aeca8a3
sources: [
    {property=, dataset=OpenStreetMap, record_id=w30171118@3, update_time=2019-05-22T20:00:56.000Z, confidence=null}, 
    {property=properties/height, dataset=USGS Lidar, record_id=null, update_time=null, confidence=null}]
type: building
```
I believe we want both sources to be displayed with a comma in between since we need to make sure that we attribute OSM correctly for these buildings from OSM.

### What browser are you seeing the problem on? What version are you running?

chrome 126.0.6478.183

### The OS you're using

Mac OS

### Steps to reproduce

1. Go to https://explore.overturemaps.org/#16.64/42.655475/-71.141057
2. select a building
3. observe that the "sources" field only has "OpenStreetMapUSGS Lidar" when it should list "OpenStreetMap, USGS Lidar"

### GERS ID of the entity in question (if applicable)

All buildings with two sources, but here is an example: 08b2a30730564fff02004d433d0138cb

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#16.64/42.655475/-71.141057

**Comment by Bonkles** [comment]
This seems like it could be related to #103.

**Comment by atiannicelli** [comment]
Yup - if you want to close this as a dup go for it. thanks!
