### ISSUE TITLE
[Feature Request] Add Map Tilting

### ISSUE THREAD

**Issue by atiannicelli** [OvertureMaps/io-site#106]
I would love the ability to tilt the map so that we are not looking straight down on the map, one such reason to do this is to more easily examine the building heights. Being able to tilt the map at a bout 45 degrees and then zoom out a bit to visualize building heights would allow us to examine if there are any building height outliers. 

I know this is probably a big ask, but it would be very cool.

**Comment by atiannicelli** [comment]
Duh... double mouse click and drag gets map tilting!!!! yay! Closing

**Comment by Bonkles** [comment]
Yeah this is easy to miss- in fact we're working on a 'first-touch' nav experience that will let you click around to various POIs to inspect the data, and that would adjust the tilt automatically depending on which POI you click. For example, if you click on the 'New York City Buildings' POI, it would set the pitch to 60 degrees, really highlighting the 3D-ness.
