### ISSUE TITLE
Wrong Street Name

### ISSUE THREAD

**Issue by dsegoviamx** [OvertureMaps/io-site#123]
This is "Pino" street (or "Calle 'Pino'"), not "Pino Suarez".

ID: 08b488e98cb6afff046fbe2ee0a0a592

**Comment by jwass** [comment]
Hi @dsegoviamx Almost all of the roads in Overture come from OpenStreetMap and this one is here: https://www.openstreetmap.org/way/645279528#map=18/29.33713/-100.95033.

If you're up for it - you can fix it there and that fix will find its way into Overture in the next release or two.
