### ISSUE TITLE
Add ability to turn on/off individual types instead of whole themes

### ISSUE THREAD

**Issue by jwass** [OvertureMaps/io-site#129]
### Description

It would be great to be able to toggle specific types in addition to whole themes. For example I might want to turn off building_parts while keeping buildings on.

### Steps to reproduce

None

### The browser URL at the time you encountered the bug

None

**Comment by Bonkles** [comment]
Yep this work was planned in #102 and is already in main- hasn't shipped to the main site yet.

**Comment by Bonkles** [comment]
Closing, this will be part of Beta 2 which will ship very soon.
