### ISSUE TITLE
Missing building:part ways

### ISSUE THREAD

**Issue by StrandedKitty** [OvertureMaps/io-site#135]
### Description

We've found another issue with missing building:part features.

There's this micromapped building that's supposed to have 7 parts and 1 outline (all ways):

<img width="1122" alt="Screenshot 2024-08-01 at 20 56 07" src="https://github.com/user-attachments/assets/0928a181-d5d5-4cd4-a230-80c435e4214d">

But what I see on [io-site](https://explore.overturemaps.org/#17.78/53.542249/9.982834/30.5/30) is that only 3 of them are present (the outline is not rendered because it's marked as `has_parts=true` I presume):

<img width="1002" alt="Screenshot 2024-08-01 at 20 57 17" src="https://github.com/user-attachments/assets/445a43a7-a8dc-40c7-bc78-e72c2e90f745">

Missing building parts are all ways with IDs 363299462, 798335331, 798335332, 798335334.

These building are missing in our tiles generated from the most recent Overture data 2024-07-22.0 too, so I imagine they are just not present in the distribution for some reason.

I also don't see any problems with how this building is mapped on OSM, tagging is totally conventional.

### Steps to reproduce

1. Visit specified location
2. Observe missing OSM building parts

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#17.78/53.542249/9.982834/30.5/30

**Comment by Bonkles** [comment]
It looks like the display issue here is broadly similar to #107 - in the tiles,  we have two buildings, one enclosed by the other. 

This *smaller*-footprint interior building has id `08b1f1532c921fff0200326268c6d2bb` and a height of 30/min_height of 7. 
<img width="821" alt="image" src="https://github.com/user-attachments/assets/ecc52b20-537a-4def-9190-43ef1df2fad8">

This *larger* building completely encompasses the smaller one, and it has id `08b1f1532c921fff0200326268c6d2bb`: 

<img width="798" alt="image" src="https://github.com/user-attachments/assets/47568166-0240-437b-bc0b-8d61bc0f24f8">


Note that there should be two other buildings inside this larger exterior building, as depicted in the pics above. @atiannicelli any clue why those other two buildings aren't there?  We're only showing the middle building, but there should be two more buildings to the left and to the right. All three appear to have the same tagging structure in OSM, with the same heights and similar overlap to the building that encircles them.

**Comment by StrandedKitty** [comment]
I don't see how this is similar to https://github.com/OvertureMaps/io-site/issues/107. This is NOT a rendering problem, just to be clear.

This looks related to https://github.com/OvertureMaps/io-site/issues/92 though.

**Comment by Bonkles** [comment]
Agreed @StrandedKitty, I should be more clear here- it looks like this issue has parts of *both* #107 and #92 in it. 

we're straight up missing some building part info in the tiles, but we're also not displaying all the building part information that *did* make it into the tiles. Either way, we have some work to do to diagnose exactly why these got left out.

**Comment by Bonkles** [comment]
Confirming that of the three building_parts that are in OSM, the july release only includes the middle one. 

Here's a rapid rendering of the .geojson I just loaded with the overturemaps py downloader. 
<img width="808" alt="image" src="https://github.com/user-attachments/assets/aa36a296-a34a-47f3-bcdf-d57230b104c2">

**Comment by Bonkles** [comment]
brought this issue to the buildings task force meeting, it seems that there are already some issues (such as https://github.com/OvertureMaps/data/issues/197) that are tracking similar. There are efforts underway to incorporate more building parts for the next release.

**Comment by atiannicelli** [comment]
Th latest canary build of explorer shows that this has been fixed in the latest 
<img width="1467" alt="Screenshot 2024-08-27 at 4 36 15 PM" src="https://github.com/user-attachments/assets/8e4af517-f6b1-4097-95de-18797a649fea">
I am going to close this as fixed (As of the August Release)
