### ISSUE TITLE
Navegación excesivamente lenta con navegador Edge

### ISSUE THREAD

**Issue by ignaciouni** [OvertureMaps/io-site#144]
### Description

Estoy intentando ver el visualizador de Overture Maps Explorer (Beta), pero cuando el zoom para alejarme del mapa y desplazarme a otra zona dejan de verse las diferentes capas del visor.
Solo me pasa con el navegador Edge

### What browser are you seeing the problem on? What version are you running?

Microsoft Edge para negocios Versión 127.0.2651.86 (Compilación oficial) (64 bits)

### The OS you're using

Win 11

### Steps to reproduce

1 Ir a https://explore.overturemaps.org/
2 Alejar el zoom
Desaparecen los elementos de los mapas y se queda la pantalla en blanco y tarda mucho en cargar los contenidos
No sucede con Firefox

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#0.92/0/10.2

**Comment by Bonkles** [comment]
Could not reproduce. 

Tested this using the Edge browser on my home PC running win10 by zooming in from zoom 1 - zoom 20 - back to zoom 1  over Manhattan Island. 

There are some points where (especially on zoom out) the map takes a bit to 'catch up' as it loads more tile data, but I did not observe the reported issue here. 

I suspect that a networking issue is perhaps preventing new tile data from being loaded, but that doesn't explain why this works on firefox and not edge.

**Comment by ignaciouni** [comment]
Ahora va un poco más rápido. Puede que sea un problema de red o problemas
temporales con la carga de datos en Edge. Gracias por la pronta respuesta.
--

[image: Departamento de Geografía y Ordenación del Territorio][image:
Facultad de Filosofía y Letras de la Universidad de Zaragoza]

José Ignacio Sánchez Carbonell
Profesor Asociado de Análisis Geográfico Regional

***@***.***

(+34) 876 553 923; Extensión: 843923

Pabellón de Geografía, despacho E3.12

C/ Pedro Cerbuna, 12, 50009, Zaragoza (España)

**Comment by Bonkles** [comment]
Glad to hear! Closing.
