### ISSUE TITLE
Update site to August dataset?

### ISSUE THREAD

**Issue by marklit** [OvertureMaps/io-site#151]
### Description

I can see from the inspector the feed is still July's. Are you going to switch it to August's PMTiles soon?

### What browser are you seeing the problem on? What version are you running?

Brave

### The OS you're using

Windows 11

### Steps to reproduce

Open the inspector in Brave, click on any of the .pmtiles links

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#18.04/59.437588/24.745717

**Comment by Bonkles** [comment]
We are going to generate tiles soon- There's going to be a couple days' lag time this month as we're still trying to make a mature runbook-led process for this.  We'll get better at this!
