### ISSUE TITLE
Overture Maps Explorer - Places Data cant be downloaded as Points for integrating them to Esri ArcGISPro

### ISSUE THREAD

**Issue by Gerdicity** [OvertureMaps/io-site#178]
### Description

Hello there,

i am not at all an expert with Python/Json etc., i just tried to download Data from Overture Maps Explorer https://explore.overturemaps.org/#15.84/48.187778/16.302516/-25.6 and the only data in Overture Maps Explorer that i can download, is the buildings-layer. This i can download as Json and then transform it into normal GIS-feature layer using ArcGISPro-Tools. 

i have no possibility to download the places-layer, which is a point layer and which i would love to use in ArcGISPro because i could categorize the POI-Places-Data and thus use it in a good way.

Is there a general bug in terms of downloading the Places-Data?
Can anyone download the Places-Data without fails? How?
thank you very much!

### What browser are you seeing the problem on? What version are you running?

Microsoft Edge

### The OS you're using

Win10

### Steps to reproduce

try to download places data (poi-point data) from 
https://explore.overturemaps.org/#15.84/48.187778/16.302516/-25.6 

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#15.84/48.187778/16.302516/-25.6

**Comment by Bonkles** [comment]
Hello! The downloads for other layers are currently in testing, and available as a test build. Try it out at explore.overturemaps.org/canary and let me know if downloading the places works for you!

**Comment by Gerdicity** [comment]
Hello there, thank you so much for your quick answer, its fantastic - that really worked now, thats amazing, im so thankful, thank you - so i got that point data now in my ArcGIS using the command Json to features. Great! All the best!

**Comment by Bonkles** [comment]
Awesome! Lots of folks reporting that the downloads 'just work' now, so we'll be promoting them to the site next week. Thanks for the report!

**Comment by Gerdicity** [comment]
Hello there again, i tried to download the POI-Data again after some while and i am encountering problems again, unfortunately! the Link you posted doesn't work anymore so im not sure either, what the corrected link was :( 
im not sure if its only me, but i'd greatly appreciate help in this regard! all the best! greetings!

**Comment by Bonkles** [comment]
Hello again, 

Ah, my fault- the 'canary' build is ephemeral and subject to change at any time. You should be able to resume using the main page ([explore.overturemaps.org](https://explore.overturemaps.org)) for the time being. If that still doesn't work for you, please do open a new bug and I can take a look. 

Thanks!

**Comment by Gerdicity** [comment]
Hello there, thank you so much for your extremely quick reply! it works now again! thank you so much! :)
