### ISSUE TITLE
CORS errors when attempting to fetch from the Overture buckets

### ISSUE THREAD

**Issue by Bonkles** [OvertureMaps/io-site#5]
I'm in the 'app-skeleton' branch trying to just get geoarrow-wasm minimally functional, i.e. capable of reading files. 

It looks to me like the app is able to instantiate the wasm and it attemps to create a new `ParquetFile` using the url I supply in the code:

https://github.com/OvertureMaps/io-site/blob/app-skeleton/site/src/main.jsx#L19

In the process of that instantiation, it looks like we do both a 'preflight' `OPTIONS` and then a 'fetch' `GET`. 

According to the dev tools console, the preflight options gets `403`d, and the fetch receives a CORS error. 

CORS Error: 
```
Access to fetch at 'https://overturemaps-us-west-2.s3.amazonaws.com/release/2023-11-14-alpha.0/theme=transportation/type=segment/part-00158-6cb89013-4ec2-4b94-8e4b-8e27c7d30865.c000.zstd.parquet' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by Bonkles** [comment]
The preflight `OPTIONS` call is as follows: 

```
fetch("https://overturemaps-us-west-2.s3.amazonaws.com/release/2023-11-14-alpha.0/theme=transportation/type=segment/part-00158-6cb89013-4ec2-4b94-8e4b-8e27c7d30865.c000.zstd.parquet", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:5173/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "OPTIONS",
  "mode": "cors",
  "credentials": "omit"
});
```

And the `GET` call is as follows: 

fetch("https://overturemaps-us-west-2.s3.amazonaws.com/release/2023-11-14-alpha.0/theme=transportation/type=segment/part-00158-6cb89013-4ec2-4b94-8e4b-8e27c7d30865.c000.zstd.parquet", {
  "headers": {
    "range": "bytes=-8",
    "sec-ch-ua": "\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\""
  },
  "referrer": "http://localhost:5173/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});

**Comment by mojodna** [comment]
I updated the CORS configuration to the following, after which the `OPTIONS` request returns a 200 rather than a 403.

```json
[
    {
        "AllowedHeaders": [
            "range"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
```

**Comment by Bonkles** [comment]
CORS errors seem to be a thing of the past. I am now able to read parquet files, seemingly!

I'm getting a valid `ParquetFile` object back and it has valid `numRows` and `numRowGroups` entries, so at least the CORS errors are a thing of the past.
