### ISSUE TITLE
Add a github issues bug nub

### ISSUE THREAD

**Issue by Bonkles** [OvertureMaps/io-site#69]
We want to give folks the ability to create bugs through the explorer site. 
So, this issue is a two-parter: 
- [ ] Create bug ingestion template yaml forms to harvest feedback. 
  - One for the data DISPLAYED (i.e. the PMTiles / inspector data)
  - One for Problems with the DOWNLOADED data
  - One for General UI / usability bugs

  example code: https://github.com/facebook/Rapid/tree/main/.github/ISSUE_TEMPLATE

- [ ] Create a bug nub / control that floats within the map (lower right?) that directs the user to the issues page we've created in the first item. 

For examples on what the bug templates look like: 

screenshot: 
<img width="1564" alt="image" src="https://github.com/OvertureMaps/io-site/assets/1887955/b7e7c603-4e68-46af-844e-4686dc5a098b">

**Comment by eti7075** [comment]
Are there any specific pieces of information that might be useful for this issue templates? So for, I have mostly added generic input fields, but there is definitely room to add more specific fields that make each bug type more specialized.

**Comment by Bonkles** [comment]
I think it's fine enough to go with *some* fields and get some user testing done. We can definitely use this during the upcoming DA summit as a point to engage the folks attending. Can you add some screenshots of what the forms look like? That way folks that don't understand where to look for the yaml files can see what is there currently.

**Comment by eti7075** [comment]
Yes! Here is the display screen shot: 
![Screenshot 2024-06-17 at 9 24 07 AM](https://github.com/OvertureMaps/io-site/assets/69924736/b7422bd5-db9d-44d3-88f0-7f5a46aebf02)

The GERS ID question is unique to the display intake form, but the other elements are common between each other intake form.

**Comment by eti7075** [comment]
Followed by the upper quarter of the form, cut off by the screen shot.
![Screenshot 2024-06-17 at 9 25 59 AM](https://github.com/OvertureMaps/io-site/assets/69924736/15c78adb-1f1c-45e3-b117-964770ef5d2f)
