### ISSUE TITLE
[Bug] Fail to display properties of road segment in Inspector Panel

### ISSUE THREAD

**Issue by ylinzhi** [OvertureMaps/io-site#74]
# **Problem**
When clicking the road segment at the transportation layer, it's expected to display properties of the road segment as below
![image](https://github.com/OvertureMaps/io-site/assets/35787039/c97f4837-1b68-450a-9ec0-718d47e7131f)

However, not all road segments have the properties successfully displayed, as below
![image](https://github.com/OvertureMaps/io-site/assets/35787039/94cc7fa6-b79b-4f94-a1d5-2c2a49615014)

# **Example area to inspect**
https://explore.overturemaps.org/#18.55/51.0335577/3.7419535

**Comment by Bonkles** [comment]
@bdon can you take a look at this?

**Comment by bdon** [comment]
Yup, this ought to affect shorter segments right now; longer ones should have all tags 

I will need to modify https://github.com/bdon/overture-tiles/blob/898a959961e8d8caac424cc74633dddbd9405556/scripts/2024-05-16-beta.0/OvertureProfile.java#L33 to properly include all tags at the deepest zoom level

**Comment by bdon** [comment]
Should be resolved by https://github.com/bdon/overture-tiles/commit/af60b5fff8a7e81b78f5d413b41d30434fc77c8b

I'm creating the updated themes now for 2024-06-13-beta.0 

Should we re-create the 2024-05-16-beta.0 tilesets - and do we want to going forward, or should we consider them "immutable" once it's a release in the past? I anticipate tilesets are "mutable" to fix things like this in the lifecycle of a release.

**Comment by Bonkles** [comment]
@ylinzhi I have published a new version of the site with @bdon's fixes at explore.overturemaps.org. Please re-open if you still see the problem!
