### ISSUE TITLE
Highlight selected feature

### ISSUE THREAD

**Issue by ylinzhi** [OvertureMaps/io-site#75]
When feature is selected and Inspector Panel is turned on,  the selected feature should be highlighted for clarity

**Comment by bdon** [comment]
This should be possible with MapLibre hover events / feature states.

**Comment by ylinzhi** [comment]
Thanks for adding this new functionality!  It works well! Just one more followup request: 
Would that be okay to highlight the selected map features in different color?  When turning off the division layer, the highlighted feature is blended with the background
<img width="1104" alt="Screenshot 2024-06-20 at 3 04 23 PM" src="https://github.com/OvertureMaps/io-site/assets/35787039/da779e8a-eddb-4d68-9c40-1e0499f6662c">

**Comment by bdon** [comment]
I set the highlighted color to White for now, it is visible when the site is on Dark Mode. Let's re-think a better highlight color.
