### ISSUE TITLE
[Bug] Division 'labels' are still visible when division layer is not selected.

### ISSUE THREAD

**Issue by eti7075** [OvertureMaps/io-site#76]
When the divisions label is not selected, some division values are still visible and clickable. These division values consist of names of places (countries, regions, counties, etc.). 
![Screenshot 2024-06-14 at 2 59 34 PM](https://github.com/OvertureMaps/io-site/assets/69924736/7b5cd50c-1bf1-4744-9a72-7bfb807b0713)

Selected in the picture above is the `United States` label, resulting in a division entity being portrayed in the inspector panel.

**Comment by bdon** [comment]
My thinking was that the division labels are useful to help navigate the map even if the division polygons/lines are turned off.

What do others think? Can we get away with not showing them? 

We could leave them displayed but ignore their interaction programatically.

**Comment by eti7075** [comment]
I think leaving them displayed but ignoring their interaction keeps the best of both worlds. They are useful in map navigation, but I think maintaining interaction even when divisions were not selected adds some inconsistency to the site. In addition, whenever the other layers become accessible to download, this could be a cause for some confusion if a 'download visible layers' option is provided.

**Comment by bdon** [comment]
See #79 for resolution
