### ISSUE TITLE
Improve builds by *not* checking in the index_bg.wasm into the public folder

### ISSUE THREAD

**Issue by Bonkles** [OvertureMaps/io-site#8]
As it stands, the vite plugin that handles wasm modules doesn't like geoparquet-wasm, so I short-circuited it to simply live inside the public folder for now. 

At the very least, this should be moved as a build-time step to copy it from node_modules into the appropriate place. 

Long term, we should get the wasm build working from within the `vite-plugin-wasm-pack`. 

Found this stackoverflow page which has a few pointers: https://stackoverflow.com/questions/72587871/how-to-include-an-wasm-npm-module-in-svelte-with-vite

I checked the geoparquet-wasm bundle and it is indeed bundling the esm dep as `--target web`, so that's good. However, there isn't a `main` property in the package.json.

**Comment by kylebarron** [comment]
The cool thing would be if `vite-plugin-wasm-pack` would let you pass in compilation features into the wasm-pack command. Because then you could take `geoarrow-rs` as a submodule and build a custom wasm dependency with only the compilation features you need (e.g. parquet)

**Comment by Bonkles** [comment]
For now this is still a static dependency, but at least it's no longer checked in. 

Fixed in commit `16ee2639fbb2bd403407f8ca006397aa5b21bebe`.
