### ISSUE TITLE
Transportation Layer Inspector Improvement

### ISSUE THREAD

**Issue by borismenkov-tomtom** [OvertureMaps/io-site#83]
### Description

Currently the class tag is rendered at the bottom of the panel and often falls below the line requiring the user to scroll down. It is one of the more important tags I want to see in the absence of styling of the transportation network. 

### What browser are you seeing the problem on? What version are you running?

Brave

### The OS you're using

Windows 11

### Steps to reproduce

select transportation element - observe order of tags.

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#18.72/43.7016616/-72.2904077

**Comment by eti7075** [comment]
This feature was added in [PR #87](https://github.com/OvertureMaps/io-site/pull/87), and was expanded to all themes when applicable.
