### ISSUE TITLE
[Bug] Unable to properly deselect features

### ISSUE THREAD

**Issue by ylinzhi** [OvertureMaps/io-site#91]
### Description

When a feature is selected, there is no way to deselect feature, except for refreshing the website.  Clicking at a blank spot only close the inspector panel, not de-highlight the selected features

### What browser are you seeing the problem on? What version are you running?

Chrome

### The OS you're using

MacOS

### Steps to reproduce

1. Click on any type features to select
2. Click on a blank spot to deselect

### GERS ID of the entity in question (if applicable)

089194ad306fffff047ffe22cd897271

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#18.15/51.505082/-0.08924

**Comment by eti7075** [comment]
This feature was added as a part of [PR #87](https://github.com/OvertureMaps/io-site/pull/87)
