### ISSUE TITLE
Missing building:part ways in NYC

### ISSUE THREAD

**Issue by StrandedKitty** [OvertureMaps/io-site#92]
### Description

I'm comparing Overture buildings with data from other OSM providers, and what I see is that there are numerous ways tagged `building:part` that are missing in your distribution.

For example, see way #289539923 (https://www.openstreetmap.org/way/289539923).

You can see that it's missing in Overture distribution if you visit this location on explore.overturemaps.org:

https://explore.overturemaps.org/#17.08/40.764901/-73.975485/38.4/10
<img width="435" alt="Screenshot 2024-07-08 at 20 32 44" src="https://github.com/OvertureMaps/io-site/assets/48140945/dc20241e-9e5a-4466-87c9-c2edceb7ba88">

### Steps to reproduce

1. Do nothing.
2. Data is not there.

### The browser URL at the time you encountered the bug

https://explore.overturemaps.org/#17.08/40.764901/-73.975485/38.4/10

**Comment by bdon** [comment]
Confirming that this does not exist in 2024-06-13-beta (from a local copy of `2024-06-13-beta.0`):

```
select * from read_parquet('/srv/data/overture/2024-06-13-beta.0/theme=buildings/type=building_part/*') where sources[1].dataset = 'OpenStreetMap' and sources[1].record_id = 'w289539923';
```

**Comment by Bonkles** [comment]
@atiannicelli to investigate here. Thanks @bdon for confirming the data is, in fact, missing.

**Comment by atiannicelli** [comment]
We've been doing some major work ok the building parts associations recently and I am happy to report that it DOES exist on the latest released version [2024-07-22.0](https://docs.overturemaps.org/release/latest/)
Here is a screen shot from the explorer.
<img width="1792" alt="Screenshot 2024-07-25 at 11 05 10 AM" src="https://github.com/user-attachments/assets/5230ae6b-58ef-4ca4-be8c-87bb0e2b9d7d">

@StrandedKitty - thanks for reporting! if you see ANY more parts that are missing or strange behavior with building parts then please let us know!

**Comment by Bonkles** [comment]
Thanks @atiannicelli! Closing.

**Comment by StrandedKitty** [comment]
Great, thanks!
