### ISSUE TITLE
Site needs support for the new Addresses theme

### ISSUE THREAD

**Issue by Bonkles** [OvertureMaps/io-site#95]
### Description

There's a new theme we should be visualizing- addresses. There's a temporary URL that we can use for just getting the data up onto the site that @bdon provided: 

https://protomaps.dev/~bdon/addresses.pmtiles

Of course this is a temp URL but we can use it for staging purposes / getting something built. 

This task ask that we: 
- [x] create an 'Addresses' layer at the top of the Z order (above everything else)
- [x] Style it with simple dots/circles/colors (nothing fancy) 
- [x] Support selection like the other layers
- [x] Add theme selector support for addresses
- [ ] Add inspector panel support for addresses (schema hasn't quite landed yet- find it in this [PR](https://github.com/OvertureMaps/schema/pull/233))

### What browser are you seeing the problem on? What version are you running?

Chrome v120

### The OS you're using

MacOs 14

### Steps to reproduce

n/a - just a feature we don't yet support. 

### GERS ID of the entity in question (if applicable)

n/a

### The browser URL at the time you encountered the bug

n/a

**Comment by eti7075** [comment]
Subject to change: Size and color of the dots - where there is address data, there is much more than other themes, so we might want to consider a small point radius to reduce clutter, and the cyan is not set in stone, but currently does a good job of being very different from other theme colorings

**Comment by bdon** [comment]
We could parameterize `ThemeTypeLayer` to make the point radius for addresses smaller:

https://github.com/OvertureMaps/io-site/blob/main/site/src/Map.jsx#L84

**Comment by bdon** [comment]
Looks good to me! I will also prepare a PR to put labels on top, since it looks awkward with points covering labels right now...
